emailGroups = {
    "standard": "igo",  # will be added to every delivery, together with project LabHead and PI
    "raw": "",  # only standard list
    "impact": "pipelineSupport",
    "access": "access",
    "wesWithCCS": "ccs",
    "ccs": "ccs",
    "pipelineDefault": "bic",
    "ski": "ski",
}

emailAddresses = {
    "igo": "zzPDL_ski_igo_delivery@mskcc.org",
    "pipelineSupport": "zzPDL_CMO_Pipeline_Support@mskcc.org",
    "access": "zzPDL_SKI_CMO_ACCESS@mskcc.org",
    "ski": "skiinnovation@mskcc.org",
    "bic": "bic-request@cbio.mskcc.org",
    "ccs": "zzPDL_CMO_TEMPO_Support@mskcc.org,skicmopm@mskcc.org",
}

genericSubject= "[IGO Data] %s Project %s "

genericContent = "Hello,<br><br>The FASTQ files for your %s Project %s have been posted to the %s shared drive. Detailed instructions available at: <a href='http://genomics.mskcc.org/accessing-your-data/'> genomics.mskcc.org/accessing-your-data </a>"

nonMSKContent = "Hello,<br><br>The FASTQ files for your %s Project %s are ready. We could not identify a shared drive for %s. Please reach out to zzPDL_SKI_IGO_DATA@mskcc.org to discuss how you can access your data."

fastQOnlyContent = "Hello,<br><br>The FASTQ files for your %s Project %s have been posted to the %s shared drive. Detailed instructions available at: <a href='http://genomics.mskcc.org/accessing-your-data/'> genomics.mskcc.org/accessing-your-data </a>"

impactContent = "Hello,<br><br>IGO processing is now complete. FASTQ files for your %s Project %s have been posted to the %s shared drive as well as transferred to the CMO Analysis Support (CAS) Team, for pipeline analysis. You will be contacted when this project is delivered to cBioPortal."

wesWithCCSContent = "Hello,<br><br>IGO processing is now complete.FASTQ files for your %s Project %s have been transferred to the CMO Computational Science (CCS) Team, for pipeline analysis. Please contact your Project Manager for updates."

accessContent = "Hello,<br><br>IGO processing is now complete. FASTQ files for your %s Project %s have been transferred to the ACCESS Analysis Team, for data quality control and standard data processing. Please contact your Project Manager for further updates."

genericAnalysisContent = "Hello,<br><br>IGO processing is now complete. FASTQ files for your %s Project %s are accessible to the Bioinformatics Core (BIC). Please go to <a href='https://bic.mskcc.org/bic/services/request/'>https://bic.mskcc.org/bic/services/request/</a> to initiate a request for analysis. "

crisprAddon = "<br>In addition, you will receive the results of the CRISPResso analysis, generated by the CRISPResso2 software. <br> For a detailed description of the output please consult https://crispresso.pinellolab.partners.org/help "

DEFAULT_ADDRESS = "naborsd@mskcc.org,mcmanamd@mskcc.org"
NEW_DEFAULT_ADDRESS = "zzPDL_SKI_IGO_DATA@mskcc.org"
SENDER_ADDRESS = "naborsd@mskcc.org"
SKI_SENDER_ADDRESS = "igoski@mskcc.org"
MSKCC_ADDRESS = "YOUR_MSKCC_ADDRESS"
NO_PM = "NO PM"
REDELIVERY_MESSAGE = """Hello,

We have linked additional fastqs to this project. Often this is caused because we resequenced a pool and already sufficiently-sequenced samples received additional reads. There are no additional charges for these reads.

"""
FOOTER = """Integrated Genomics Operations,
Center for Molecular Oncology,
Memorial Sloan Kettering Cancer Center, New York.
http://cmo.mskcc.org/"""

def getAliases(self):
        aliases = defaultdict(str)
        aliases["a-haimovitz-friedman@ski.mskcc.org"] = "haimovia"
        aliases["a-zelenetz@mskcc.org"] = "zeleneta"
        aliases["a-zelenetz@ski.mskcc.org"] = "zeleneta"
        aliases["d-scheinberg@ski.mskcc.org"] = "scheinbd"
        aliases["f-giancotti@ski.mskcc.org"] = "giancotf"
        aliases["j-massague@ski.mskcc.org"] = "massaguej"
        aliases["k-anderson@ski.mskcc.org"] = "kanderson"
        aliases["m-baylies@ski.mskcc.org"] = "bayliesm"
        aliases["m-jasin@ski.mskcc.org"] = "jasinm"
        aliases["m-mcdevitt@ski.mskcc.org"] = "m-mcdevitt"
        aliases["m-moore@ski.mskcc.org"] = "moorem"
        aliases["m-ptashne@ski.mskcc.org"] = "ptashne"
        aliases["m-sadelain@ski.mskcc.org"] = "sadelaim"
        aliases["m-van-den-brink@ski.mskcc.org"] = "vandenbm"
        aliases["p-tempst@ski.mskcc.org"] = "tempstp"
        aliases["r-benezra@ski.mskcc.org"] = "benezrar"
        aliases["r-kolesnick@ski.mskcc.org"] = "rkolesnick"
        aliases["s-keeney@ski.mskcc.org"] = "keeneys"
        aliases["s-shuman@ski.mskcc.org"] = "sshuman"
        aliases["w-mark@ski.mskcc.org"] = "markw"

        return aliases